name: image_view
services:
  image_view_website:
    container_name: image_view
    ports:
      - 5050:5050
    volumes:
      - pictures:/uploads
    environment:
      FLASK_SECRET_KEY: lsdkjffodsfj0wes
    image: image_view

volumes:
  pictures: